import { Request, Response } from "express";

const ministries = [
  "Citizens Services",
  "Justice",
  "Children and Family Development",
  "Environment and Climate Change Strategy",
  "Transportation and Infrastructure",
  "Social Development and Poverty Reduction",
  "Finance",
  "BC Public Service Agency",
  "Municipal Affairs",
  "Health",
  "Housing",
  "Jobs, Economic Development and Innovation",
  "Officers Of The Legislature",
  "Education and Child Care",
  "Water, Land and Resource Stewardship",
  "Forests",
  "Energy, Mines and Low Carbon Innovation",
  "Indigenous Relations and Reconciliation",
  "Post-Secondary Education and Future Skills",
  "BC Pension Corp",
  "Labour",
];

const bands = [
  {
    name: "BAND 1",
    minValue: 0,
    maxValue: 40000,
  },
  {
    name: "BAND 2",
    minValue: 30000,
    maxValue: 50000,
  },
  {
    name: "BAND 3",
    minValue: 40000,
    maxValue: 60000,
  },
  {
    name: "BAND 4",
    minValue: 50000,
    maxValue: 70000,
  },
  {
    name: "BAND 5",
    minValue: 60000,
    maxValue: 80000,
  },
  {
    name: "BAND 6",
    minValue: 70000,
    maxValue: 90000,
  },
];

const titles = [
  "Administrative Coordinator",
  "Associate Consultant",
  "BC Moving Agent",
  "Business Support Officer",
  "Call Centre Supervisor",
  "Client Assistant",
  "Client Services Administrator",
  "Contract Audit Analyst",
  "Contract Coordinator",
  "Contract Officer",
  "Copyright Officer",
  "Disposal Associate",
  "Division Records Analyst",
  "Drawings Coordinator",
  "Facilities Advisor",
  "Finance & Contract Officer",
  "Finance&Contract Officer",
  "Information Officer",
  "Integration Assistant",
  "Jr. FOI Analyst",
  "Junior FOI Analyst",
  "Junior Program Analyst",
  "Leasing Assistant",
  "Ministry Records Analyst",
  "MPDP Team Lead",
  "Procurement & Contract Officer",
  "Procurement Coordinator",
  "Production Coordinator",
  "Program Coordinator",
  "Project Administrator",
  "Project and Promotions Adminis",
  "Project Assistant",
  "Project Coordinator",
  "Projects & Engage Coordinator",
  "Property Analyst",
  "Protocol Giftware Officer",
  "Purchasing & Supply Chain Sup.",
  "Purchasing&Inventory Officer",
  "Records Advisor",
  "Registries Analyst",
  "Registries Anyalyst",
  "Supervisor, Network Stockroom",
  "Training Coordinator",
  "Account Manager",
  "Administrative Officer R18",
  "Analyst",
  "Asset Inv Rcvy Disposal Agt",
  "Bus App Analyst IM/IT Capital",
  "Bus Appl Analyst, Data Governa",
  "Business Analyst",
  "Business Application Analyst",
  "Business Development Officer",
  "Business Program Analyst",
  "Citizen Engagement Analyst",
  "Client Information Analyst",
  "Community Manager",
  "Community Manager (ShareSpace)",
  "Community Mgr",
  "Contract Analyst",
  "Contract Policy Advisor",
  "Coordinator, Corporate Ops",
  "CSA Administrator",
  "Customer Account Manager",
  "Digital Project Coordinator",
  "Disposal Agent",
  "Facilities Coordinator",
  "FOI Analyst",
  "Grant Analyst",
  "Information&PrivacyCoordinator",
  "IT Disposal Supervisor",
  "IT Project Coordinator",
  "Lease Analyst",
  "Leasing Analyst",
  "Manager, Administration",
  "Manager, Business Operations",
  "Manager, Card Prod. & Scanning",
  "Manager, Mail Preparation",
  "Manager, Print Service",
  "Mgr, Admin & Support Services",
  "Mgr, Mail Processing & Dist",
  "Mgr. Education Sector Projects",
  "Office Manager",
  "Outreach Liaison Officer",
  "Portfolio Coordinator",
  "Print Agent",
  "Print Purchasing Associate",
  "Print Purchasing Specialist",
  "Procurement & Contract Analyst",
  "Procurement & Contract Officer",
  "Procurement and Contract Analy",
  "Procurement Contract Analyst",
  "Procurement/Contract Analyst",
  "Prog Mgr Customer Serv & Sales",
  "Program Coordinator",
  "Project Administrator",
  "Project Analyst",
  "Project Coordinator",
  "Project Coordinator & Web Lead",
  "Protocol Giftware Administratr",
  "Purchasing Agent",
  "Records Analyst",
  "Records Centre Services Admin",
  "Records Mgmt Systems Admin",
  "Records Mngmt Systems Admin",
  "Recruiter",
  "Regional Supervisor",
  "RMS Administrator",
  "Senior Print Administrator",
  "Senior Registries Analyst",
  "Stores Worker",
  "Supervisor, Client Relations",
  "Supervisor, Victoria Operation",
  "Team Lead Administration",
  "Team Lead, Admin &Adjudication",
  "Team Lead, Finance and Admin",
  "Team Lead, Intake Support",
  "Training Analyst",
  "Audit & Assurance Advisor",
  "Branch Business Manager",
  "Bus Application Adv, Data Gove",
  "Bus.Ops & Client Sup. & Proc.",
  "Business Application Advisor",
  "Business Applications Advisor",
  "Business Relationship Coord",
  "Citizen Engagement Analyst",
  "Client Relationship Manager",
  "Content Designer",
  "Contract Administrator",
  "Contract Analyst",
  "Contract Management Analyst",
  "Contract Performance Analyst",
  "DIS Operations Analyst",
  "Divisional Comm and Web Lead",
  "EDRMS Configuration Analyst",
  "Energy Infrastructure Officer",
  "Facilities Officer",
  "FOI - Records Mgmt. Team Lead",
  "FOI Analyst",
  "Government Records Analyst",
  "Indigenous Partnerships Coord",
  "Info Sched Developer & Report",
  "Integration Engagement Analyst",
  "Interior Designer",
  "Investigative Analyst",
  "Investment Planning Analyst",
  "Junior Lease Manager",
  "Lean Advisor",
  "Lean Analyst",
  "Learning Specialist",
  "Manager,  Finance & Info. Syst",
  "Manager, Accounting & Admin.",
  "Manager, Warehouse & Logistics",
  "Mgr Purchasing&Client relation",
  "MGR, Business Ops and Support",
  "Mgr, Customer Service & Sales",
  "MPDP Supervisor",
  "Negotiations Analyst",
  "Operations Coordinator",
  "Operations Manager",
  "Planning Analyst",
  "Planning and Communica Analyst",
  "Planning Coordinator",
  "Policy Analyst",
  "Practice Consultant",
  "Print Procurement Specialist",
  "Privacy Analyst",
  "Privacy Investigative Analyst",
  "Prj Mgmt Analyst: Early Learn.",
  "Procure & Supply Prog Analyst",
  "Program Analyst",
  "Project Analyst",
  "Project Integration Analyst",
  "Project Management Analyst",
  "Property Tax Analyst",
  "Quality Assurance Analyst",
  "Real Estate Analyst",
  "Records Management App Advisor",
  "Risk Assesment Investigator",
  "Security Business Advisor",
  "Senior FOI Analyst",
  "Senior Records Analyst",
  "Sr Gov Records Analyst",
  "Sr Manager Comm & Change Mgmt",
  "Sr. Citizen Engag Analyst",
  "Sr. FOI Analyst",
  "Sr. Gov Records Analyst",
  "Sr. Government Records Analyst",
  "Team Lead Supervisor",
  "Team Lead Supervisor/ Sales",
  "Team Lead, Registries",
  "Team Lead/Program Analyst",
  "Team Leader Supervisor",
  "Trainer",
  "Training Specialist",
  "Training Specialist, Serv Del",
  "User Exp Content Strategist",
  "UX Web Content Strategist",
  "Visual Communications Designer",
  "Web Content Strategist",
  "Workspace Provisioning Coord",
  "Analyst, Technical Architectur",
  "Bus Oper, Client Supp and Proc",
  "Business Analyst",
  "Business Continuity Advisor",
  "Business Writer",
  "Change Management Advisor",
  "Citizen Engagement Planner",
  "Client Manager Onboarding Lead",
  "Comm & Engage Specialist",
  "Comm Engagement & Web Lead",
  "Comm. & Records Analyst",
  "Communications Specialist/Lead",
  "Content Strategy & Engage Spec",
  "Contract & Procure Specialist",
  "Contract & Procurement Spec",
  "Contract and Procurement Spec",
  "Contract Management  Analyst",
  "Contract Management Analyst",
  "Contract Perform Officer Proj",
  "Contract Performance Analyst",
  "Contract Performance Manager",
  "Contract Performance Officer",
  "Contract Performance Officers",
  "Contract Specialist",
  "Contract& Procuremt Specialist",
  "Coord Education and Training",
  "Coord., Education & Training",
  "Coord., Learn. and Development",
  "Corporate Contract Specialist",
  "Digital Engagement Manager",
  "Digital Era Learning Strategis",
  "Digital Information Strategies",
  "Digital Talent Analyst",
  "Education & Training Lead",
  "Energy & Climate Chang Manager",
  "Engagement Specialist",
  "Event Coordinator",
  "FOI Specialist",
  "Governance & Perf Rep Analyst",
  "Innov Strategist - Cntd Comm",
  "Intelligence and Support",
  "Investigator",
  "Investment Planning Analyst",
  "Learning & Development Coord",
  "Learning and Development Lead",
  "Manager, Business Development",
  "Mgr Contracts & Performance",
  "Mgr Procurement&Supply Chain",
  "Mgr, Projects & Legislation",
  "Operations Manager",
  "Outreach Program Manager",
  "Performance Evaluation Analyst",
  "Planning & Performance Advisor",
  "Planning & Performance Analyst",
  "Policy Analyst",
  "Policy Analyst- Connected Comm",
  "Policy and Legislative Analyst",
  "Policy/Program Analyst",
  "Privacy Advisor",
  "Privacy Analyst",
  "Privacy and Policy Advisor",
  "Procure Contract Specialist",
  "Procure. & Contract Specialist",
  "Procurement & Contract Spec",
  "Procurement Contract Spec",
  "Procurement Contract Specialis",
  "Procurement Specialist",
  "Procurement/Contract Analyst",
  "Procurement/Contract Specialis",
  "Procurement/ContractSpecialist",
  "Production Manager",
  "Prog Eval Analyst, Data Govern",
  "Program Evaluation Analyst",
  "Proj. Mgr., Comms & Engagement",
  "Project Coord., Del Mgt Serv.",
  "Project Coordinator",
  "Real Estate Advisor",
  "Records Centre Services Mgr",
  "Scrum Master",
  "Scrum Master, Dev Ops",
  "Senior Analyst",
  "Senior Lean Advisor",
  "Senior Planning Advisor",
  "Senior Planning Analyst",
  "Senior Planning Improvement Ad",
  "Senior Program Analyst",
  "Senior Program Manager",
  "Senior Program Manager, LeanBC",
  "Senior Project Management Advi",
  "Senior Project Manager",
  "Senior Project Manager Advisor",
  "Senior Project Manager Analyst",
  "Senior Project Mgmt Advisor",
  "Senior Project Mgmt Analyst",
  "Sr Proj Management Analyst",
  "Sr Project Management Advisor",
  "Sr Project Management Analyst",
  "Sr Project Mgmt Advisor",
  "Sr Stakeholder Relations Anal",
  "Sr. Project Management Advisor",
  "Sr. Project Management Analyst",
  "Sr. Project Mgmt Advisor",
  "Sr. Project Mgmt Analyst",
  "Sr. Telecom Business Analyst",
  "Sustainability & Outreach Lead",
  "Team Lead, RM System Admin",
  "TL Records Management Learning",
  "Training Analyst",
  "User Experience Researcher",
  "Archive & Records Planning Mgr",
  "Business & Project Svcs Office",
  "Business Service Manager",
  "Business Services Manager",
  "Client Communications Manager",
  "Client Services Manager",
  "Corp Archives Rec Plan Mgr",
  "Engagement Lead",
  "FOI Team Lead",
  "IMA Client Services Manager",
  "Manager, Emergency Mgmt",
  "Mgr, Contracts & Bus Planning",
  "Mgr, Min.Emerg.Planning&Resp.",
  "ORCS Developer",
  "Procurement/Contract Lead",
  "Project Manager",
  "Records Officer",
  "Senior Analyst",
  "Senior Policy Analyst",
  "Senior Program Analyst",
  "Senior Program Developer",
  "Senior Program Manager",
  "Sernr Planning & Improve Advis",
  "Snr Planning & Improve Advisor",
  "Sr Planning & Perf Advisor",
  "Sr Prog Dev, Digital Govmt",
  "Sr Real Estate Proj Mgr",
  "Sr User Experience Researcher",
  "Sr. Prog Developer",
  "Sustainability Program Manager",
  "Team Lead",
  "Team Lead, Citizen Engagement",
  "Team Lead, Planning Analysts",
  "Assistant Negotiator",
  "Mgr, Intellectual Property",
  "Analyst",
  "Contract Planning Specialist",
  "Government Agent",
  "Manager of Operations",
  "Manager, CIO Operations",
  "Manager, Contracts",
  "Manager, Finance",
  "Manager, Finance and Admin",
  "Manager, Information & Privacy",
  "Mgr, e-Procurement Solutions",
  "Ministry CI and Lean Advisor",
  "Mngr, Ideas Evolution",
  "Project Manager",
  "Senior Audit Advisor",
  "Senior Financial Analyst",
  "Senior Printing Agent",
  "Team Lead, Property Superint.",
  "Archivist",
  "Digital Info Strat Archivist",
  "Senior Digital Archivist",
  "Associate Deputy Minister",
  "Associate DM & Gov CIO",
  "Executive Coordinator",
  "Information Control Officer",
  "Legislative Program Manager",
  "Manager Division Operations",
  "Manager, Business Enablement",
  "Manager, Divisional Operations",
  "Manager, Facilities",
  "Mgr of Divisional Operations",
  "Mgr, Division Operations",
  "Printing Agent",
  "Senior Analyst",
  "Senior Project Analyst",
  "SHR Analyst",
  "Sr Analyst, Student Outcomes",
  "Sr Print & Procurement Agent",
  "Assist Dir, Crown Publications",
  "Assist Director, BC Mail Plus",
  "Assistant Director",
  "Assistant Director AIR",
  "Asst Dir, Product Dist Centre",
  "Business Manager",
  "Contract Performance Manager",
  "Corporate Communications Mgr",
  "Corporate Learning Specialist",
  "Corporate Services Manager",
  "DIrector, Lean",
  "Facilities Manager",
  "Funding Program Manager",
  "Government Agent",
  "Lean Consultant",
  "Learning Designer",
  "Manager",
  "Manager Awareness",
  "Manager Business Operation",
  "Manager Corporate Initiatives",
  "Manager of Operations",
  "Manager Service Design&Integr",
  "Manager, Bus Ops & Projects",
  "Manager, Change Management",
  "Manager, Content Design",
  "Manager, Digital Partnerships",
  "Manager, Exec Operations",
  "Manager, Finance",
  "Manager, Financial Services",
  "Manager, Human Resources/Workf",
  "Manager, Intake",
  "Manager, Print Srvc & Proc Sol",
  "Manager, Procurement",
  "Manager, Service Design",
  "Manager, Service Design & Int",
  "Manager, Service Practice",
  "Manager, Strategy and Support",
  "Manager, Workforce Planning",
  "Mgr App Architecture & Develop",
  "Mgr Corp Reporting & Planning",
  "Mgr Fin Serv Policy & Controls",
  "Mgr, Accounting & Reporting",
  "Mgr, Baccalaureate Grad Survey",
  "Mgr, Budgets & Finan. Analysis",
  "Mgr, Client &Customer Surveys",
  "Mgr, Cont & Stakeholder Rel",
  "Mgr, Fin Planning and Analysis",
  "Mgr, Financial & Client Serv",
  "Mgr, Public Sect Resrch & Eval",
  "Mgr, Qlty Assurance & Rel Mgmt",
  "Mgr, Registries Operations",
  "Mgr, Research & Development",
  "Mgr, Survey Design & Analysis",
  "Mgr,StrategicPlann&StakeCommun",
  "MgrContract&StakeholdRelations",
  "Portfolio Manager",
  "Pricing Analyst",
  "Project Manager",
  "Security Manager",
  "Senior Auditor",
  "Senior Financial Anaylst",
  "Senior Investigator",
  "Senior Policy & Leg Analyst",
  "Senior Project Manager",
  "SHR Advisor",
  "SHR Consultant EDI",
  "SHR Planner",
  "SHR Plannner",
  "SHR, Learning Consultant",
  "Sr Mgr, Financ Planning & Rpt",
  "Sr Mgr, Financial Plan & Rpt",
  "Sr. Auditor",
  "Sr. Investigator",
  "Strategic Planning Lead",
  "Technical Services Manager",
  "Transition Lead",
  "Workplace Planner",
  "Area Director",
  "BTA (Electric/Struc Cabling)",
  "Chapter Lead, DevOps",
  "Chapter Lead, Full Stack Dev",
  "Chapter Lead, Scrum Master",
  "Client Relations Director",
  "Data Project Director",
  "Deputy Registrar",
  "Development Manager",
  "Dir & Sr Financial Strategist",
  "Dir BC Bid Ops and Help Desk",
  "Dir Business Planning & Eng",
  "Dir Intellectual Property Prog",
  "Dir Org Change Management",
  "Dir, Bus Planning & Engagement",
  "Dir, Business and Project Serv",
  "Dir, Business Management",
  "Dir, Contract Tech Stewardship",
  "Dir, Divisional Operations",
  "Dir, Engage Design & Plan",
  "Dir, Govt IM Training",
  "Dir, Info Practices Transform",
  "Dir, Multi Language Governance",
  "Dir, Multilanguage Prog Dev",
  "Dir, People, Culture & Perform",
  "Dir, Proj & Business Services",
  "Dir, Stakeholder Engagement",
  "Dir, Strat Transform & Culture",
  "Dir, Strategic Project Support",
  "Dir, Strategic Wrkforc Initiat",
  "Dir, Workforce Planning/Report",
  "Dir. Community Engage&Planning",
  "Dir. Performance & Evaluation",
  "Dir., Comm's & Change Mgmt",
  "Dir., Perf Planning & Res Mgmt",
  "Dir.Stakeholder Eng. & Govern.",
  "Director",
  "Director Business Management",
  "Director Business Systems",
  "Director Governance&Community",
  "Director of Client Relations",
  "Director of Procurement",
  "Director Stakeholder Relations",
  "Director, Analytics and Tools",
  "Director, Bus Relationship Mgm",
  "Director, Client Relations",
  "Director, Contact Centres",
  "Director, Contract Performance",
  "Director, Corporate Comms",
  "Director, Digital Academy",
  "Director, Digital Operations",
  "Director, Executive Operations",
  "Director, FOI Modernization",
  "Director, Health Contact Centr",
  "Director, Indigenous Relations",
  "Director, Marketplace Access",
  "Director, MPDP",
  "Director, MPDP - IT",
  "Director, Opportunity Developm",
  "Director, Outreach User Exper",
  "Director, People Development",
  "Director, Policy & Legislation",
  "Director, Practice and Policy",
  "Director, Procurement",
  "Director, Product Development",
  "Director, SE & Governance",
  "Director, Service Design & Int",
  "Director, Strategic Partners",
  "Director, Strategy and Design",
  "Director, Strategy and Support",
  "Director, Talent Management",
  "Director, Transformation",
  "Director,Pub Sector Rsch&Eval.",
  "Environmental Lead",
  "Exec Dir, Strategic Initiative",
  "Lead Business Agility Services",
  "Lease Manager",
  "Lease Services Manager",
  "Manager",
  "Manager of Procurement",
  "Manager of Service Operations",
  "Manager, Access to Info.",
  "Manager, Access to Information",
  "Manager, Capital Management Un",
  "Manager, Client Services",
  "Manager, CRM",
  "Manager, Governance",
  "Manager, Investigations&Audits",
  "Manager, Leg & Special Project",
  "Manager, Leg. & Special Proj.",
  "Manager, Legislation & Policy",
  "Manager, Operational Initiativ",
  "Manager, Privacy Operations",
  "Manager, Privacy Policy",
  "Manager, Program Finance",
  "Manager, Security Operations",
  "Manager, Technical Operations",
  "Manager, Training",
  "Mgr Inegrated Prgm Marketing",
  "Mgr Network Technical Services",
  "Mgr Partner Relations",
  "Mgr Real Estate Partnerships",
  "Mgr, Access to Information",
  "Mgr, Central Agency Operations",
  "Mgr, Directory & Access",
  "Mgr,SocialMedia,Mobile&Webcast",
  "Mgr. Information Policy",
  "Mgr., Secur. Invest & Forensic",
  "Operations Analyst",
  "Operations Performance Manager",
  "Oversight Performance Manager",
  "Partner Relationship Manager",
  "Policy & Program Analyst",
  "Policy and Legislative Analyst",
  "Procurement Director",
  "Product Dir. DevOps Cont. Plat",
  "Product Owner",
  "Project Dir, Ent. Risk Mgmt",
  "Project Director",
  "Project Officer",
  "Project Services Team Lead",
  "Real Estate Manager",
  "Recruitment Specialist",
  "Senior Data Scientist",
  "Senior Lease Manager",
  "Senior Manager",
  "Senior Product Manager",
  "Senior Product Owner",
  "Senior Project Manager",
  "Service Design Chapter Lead",
  "Services Team Lead",
  "Snr Mgr Asset Investment Prgms",
  "Snr Mgr Digitl Publishg & Tech",
  "Snr Product Manager DigiMod",
  "Snr Product Mngr Dgtl Experien",
  "SR Manager, Engagement & Comms",
  "Sr Mgr Contract Int & Perf",
  "Sr Mgr Finance & Decision Supp",
  "Sr Mgr, Corporate Projects",
  "Sr Mgr, Digital Identity&Trust",
  "Sr Mgr, Finance & Decision Sup",
  "Sr Mgr, Finance & Decisions",
  "Sr Mgr, Integration and Engage",
  "Sr Privacy & Policy Advisor",
  "Sr. Advisor",
  "Sr. Manager, Bus Ops & Proj",
  "Sr. Mgr., Contract Int. & Perf",
  "Sr. Privacy and Policy Advisor",
  "Sr. Product Manager",
  "Sr. Product Mgr Chapter Lead",
  "Team Lead, Consultant",
  "Team Lead, Data Governance",
  "Team Lead, IMIT",
  "Team Lead, Tech Value",
  "Title Product Owner",
  "TL, Workplace Strat & Planning",
  "Band 4",
  "Comm. & Collaboration Services",
  "Dir Client Engmt & Serv Del",
  "Dir Cybersecur Intelli & Inves",
  "Dir Data Sc Ptnshps & Pop Stat",
  "Dir Engage and Digital Srvs",
  "Dir Financial Planning & Repor",
  "Dir Infrastructure and Strateg",
  "Dir Service Transformation",
  "Dir Strat Priv Pol & Training",
  "Dir Strgic Acquistns & Tec Pro",
  "Dir Workplace Development",
  "Dir, Application Management",
  "Dir, Arch & Product Develop",
  "Dir, Archival&Rec Initiatives",
  "Dir, Budgets & Corp Reporting",
  "Dir, Bus Planning & Projects",
  "Dir, Client Relationship Mgmt",
  "Dir, Data Sharing and Intake",
  "Dir, Dig Partner & Invest",
  "Dir, Digital Investment",
  "Dir, Digital Investment Office",
  "Dir, Digital Transformation",
  "Dir, Enterprise Arch & Adv Se",
  "Dir, Enterprise Architecture",
  "Dir, Financial Planning & Rpt",
  "Dir, Info Privacy & Security",
  "Dir, IT Inc Mgmt & Bus Cont.",
  "Dir, Modernization &Innovation",
  "Dir, Ops & Privacy Mgmt",
  "Dir, Privacy & Security Design",
  "Dir, Problem & Change Mgmt.",
  "Dir, Real Est & Stkhold Eng",
  "Dir, Serv Solution & Expansion",
  "Dir, Serv.Solution & Expansion",
  "Dir, Service Management Srvs",
  "Dir, Strategic Policy",
  "Dir,Private & Public Cloud Srv",
  "Dir. Client Eng & Serv Del",
  "Dir. Fin Pol, Report ing &Oper",
  "Dir. Info Solutions & Transfor",
  "Dir. Product Distribution Cent",
  "Dir. Project and Bus Services",
  "Dir., Digital Transformation",
  "Dir., Fac. Mngmnt & Sec. Off.",
  "Dir., Identity & Access Mgmt",
  "Dir., Indigenous Data Govern.",
  "Dir., Info. Mgmt & Strat Init",
  "Dir., Service & Technical Ops.",
  "Dir., Workplace Strateg & Plan",
  "Dir.,Tech Steward, Workst Serv",
  "Director",
  "Director Asset Portfolio",
  "Director BC Mail Plus",
  "Director Bus Serv & Branch Ops",
  "Director Business HR Strategy",
  "Director Deal Management",
  "Director Digital Transform",
  "Director Gov Ent Network Srvcs",
  "Director IM Practice Reviews",
  "Director Investigations",
  "Director Investment Management",
  "Director of Accounting",
  "Director of Finance",
  "Director of Operations",
  "Director of Service Operations",
  "Director Product & Service Mgt",
  "Director Prov Soc & Econ Stats",
  "Director Security, Priv & Comp",
  "Director Strategic Initiatives",
  "Director, Accommodation Proj.",
  "Director, Analysis & Dec Suppt",
  "Director, Application Mgmt",
  "Director, Business Management",
  "Director, Capital Projects",
  "Director, Client Services",
  "Director, Contract Management",
  "Director, Corp Sustainability",
  "Director, Corporate Planning",
  "Director, Data Insights",
  "Director, Demographic Analysis",
  "Director, Developer Experience",
  "Director, Digital Delivery",
  "Director, Enterprise Comm Serv",
  "Director, Finance",
  "Director, Finance and Strategy",
  "Director, Financial Services",
  "Director, Information Security",
  "Director, King's Printer",
  "Director, LeanBC",
  "Director, Leasing Services",
  "Director, Order Management",
  "Director, Org Change Mgmt",
  "Director, Pharmacy",
  "Director, Policy & Legislation",
  "Director, Procurement Manageme",
  "Director, Program Development",
  "Director, Project Management",
  "Director, Service Management",
  "Director, Service Operations",
  "Director, Strategic Initiative",
  "Director, Strategic Policy",
  "Director, Strategic Policy BL",
  "Director, Strategic Projects",
  "Director, Strategic Services",
  "Director, Technical Services",
  "Director, TechnicalStewardship",
  "Director, Technology",
  "Director, Telecommunications",
  "Director, Workplace Develop SB",
  "Director,Contracts,Device Serv",
  "Director,Indigenous Engagement",
  "Director,Portfolio & Reporting",
  "ED, Service Transformation",
  "Exec Advisor, Comm & Strat",
  "Exec. Dir., Project Mgmt.",
  "Project Director",
  "Project Director IM/IT",
  "Provincial Director of Ops",
  "Sen Dir, Access & Open Informa",
  "Senior Director",
  "Senior Director, Procurement",
  "Senior Portfolio Director",
  "Snr Dir. Distribution Logistic",
  "Sr Dir Bus Integration & Gov",
  "Sr Dir Proc & Supply Pol Innov",
  "Sr Dir Strat & Portfilio Mgmt",
  "Sr Dir Strat Prior&Proj Del Of",
  "Sr Dir Strategy, Rpt & Engage",
  "Sr Dir, Bus & Comm Solutions",
  "Sr Dir, Change Mgmt & Sustain",
  "Sr Dir, Digi Engagem Solutions",
  "Sr Dir, Digital Talent Careers",
  "Sr Dir, eProcurment & Src Slts",
  "Sr Dir, Online Svcs Solutions",
  "Sr Dir, Portfolio Strat & Algn",
  "Sr Dir, Svcs & Content Design",
  "Sr Director, Analytics",
  "Sr Director, Connected Service",
  "Sr Director, Digital Portfolio",
  "Sr. Dir  Regulatory & Permit",
  "Sr. Dir. BC Bid Operations",
  "Sr. Dir., Strategic Engagement",
  "Sr. Director",
  "Sr. Director Connectivity Init",
  "Sr. Director, Client Relations",
  "Sr. Director, Digital Policy",
  "Srv Lead Stkhd Eng & Proc Plan",
  "Chief Human Resources Officer",
  "ED & Reg, BC Reg & Online Svcs",
  "ED Strategic Initiatives RProp",
  "ED, Business Transformation",
  "ED, Connected Communities",
  "ED, Corporate Initiatives",
  "ED, Corporate Perf & Engage",
  "ED, Info Access Operation",
  "ED, Info Mgmt Innovation",
  "ED, Negotiations",
  "ED, Negotiations, MWTS",
  "ED, Negotiations, SDS",
  "ED, Partnerships and Capacity",
  "ED, Procurement Transformation",
  "ED, Strategic Pol&Legislation",
  "ED., Digital Strat. & Delivery",
  "Ex Dir PublicEngagement&Design",
  "Exe Dir, Data & Digi Platforms",
  "Exe Dir, Provincial IDIM Progr",
  "Exe Dir, Service Management",
  "Exec Dir - Corporate Projects",
  "Exec Dir & MCIO, Infom Mgmt",
  "Exec Dir Accommodation Mgmt",
  "Exec Dir Corporate Performance",
  "Exec Dir Facilities Mgmnt Svcs",
  "Exec Dir Strat Partners Office",
  "Exec Dir Strategic RE Services",
  "Exec Dir, Asset Management",
  "Exec Dir, Contract Mgmt&Negoti",
  "Exec Dir, Digital Capacity",
  "Exec Dir, Digital Invest Offic",
  "Exec Dir, Finance & Strategy",
  "Exec Dir, Info Transformation",
  "Exec Dir, Procurement Services",
  "Exec Dir, Real Estate Bus Srvc",
  "Exec Dir, Service Delivery",
  "Exec Dir, Strat Proj&Planning",
  "Exec Dir,Serv Architec & Plann",
  "Exec Dir., Device Services",
  "Exec Direc, DevExchange DevOps",
  "Exec Director Hosting Services",
  "Exec Director Network BC",
  "Exec Director Pol &Leg, CP, SO",
  "Exec Director, Client Services",
  "Exec Director, Exchange Lab",
  "Exec Director, Supply Services",
  "Exec. Dir Info Mngmt Cmplince",
  "Exec. Dir, Corporate Privacy",
  "Exec. Dir., Workplace Dev Serv",
  "Exec. Director, Digital Trust",
  "Executive Director",
  "Executive Director and CFO",
  "Executive Director, Cloud Serv",
  "Executive Director, ISS",
  "Executive Director, WTSP",
  "Chief Digital Identity & Trust",
  "Chief Digital Officer",
  "Exec Dir, Corp Online Services",
  "Exec Director, Info Security",
  "Senior Executive Director",
  "Senior Executive Director ICT",
  "Strat Adv, Connectivity Permit",
  "Executive Assistant",
  "Ministerial Advisor",
  "Chief of Staff",
  "Building Tech Adv (Mech/Plumb)",
  "Development Manager",
  "Dir, Service Design & Integrat",
  "Director",
  "Director, Client Relations",
  "Director, Finance Negotiations",
  "Director, Financial Operations",
  "Director, Info Prov & Rec Serv",
  "Director, Purchasing Services",
  "Director, SPCISO",
  "Director, Transformation",
  "Exec Dir, Finance",
  "Knowledge Manager",
  "Manager",
  "Manager, Application Managemen",
  "Manager, Finance and Admin.",
  "Manager, Oper Priv & Proj",
  "Mgr, Strateg Align Secretariat",
  "Mgr,ContactCentre&ClientSvcs",
  "Mgr,Strategic Privacy Initiati",
  "Project Director",
  "PS&S Business Systems Project",
  "Regional Director",
  "Regional Director, Service BC",
  "Senior Workplace Planner",
  "Accounts Clerk",
  "Admin Assistant / Receptionist",
  "Admin Support",
  "Administration Clerk",
  "Administrative  Assistant",
  "Administrative Assistant",
  "Administrative Assistant",
  "Administrative Coordinator",
  "Administrative Support",
  "Branch Assistant",
  "Business Support Clerk",
  "Data Integrity Clerk",
  "Facilities Clerk",
  "Finance and Admin Assistant",
  "Finance and Admin Clerk",
  "Finance Services Rep",
  "Financial Clerk",
  "Financial Services Clerk",
  "Intake Support Clerk",
  "ITC Team Assistant",
  "Legal & Collec. Support Clerk",
  "MPDP Clerk",
  "MPDP Exceptions Clerk",
  "MPDP Production Clerk",
  "Operations Support Clerk",
  "Pay Technician",
  "Postal Clerk",
  "Print Customer RelationshipClk",
  "Procurement Clerk",
  "Product Support Clerk",
  "Program and Admin. Coordinator",
  "Program Assistant",
  "Program Support Clerk",
  "Publications & Records Tech",
  "Quality Assurance Advisor",
  "Records Admin Clerk",
  "Records Cent Serv Intake Coord",
  "Records Clerk",
  "Recruitment Assistant",
  "Registries Support Clerk",
  "Scanning Technician",
  "Shipper/Receiver -Loading Dock",
  "Shipper/Receiver Position",
  "Supply Chain Support Clerk",
  "Accounts Clerk",
  "Admin Assis/Evidence Custodian",
  "Administrative Assistant",
  "Administrative Assistant",
  "Administrative Coordinator",
  "Administrative Coordinator,",
  "Associate Production Coord",
  "AUX Customer Service Rep",
  "Aux. Customer Service Rep",
  "Auxiliary Customer Service Rep",
  "BC Bid Support Clerk",
  "Branch Admin Coordinator",
  "Branch Coordinator",
  "Branch Operations Admin",
  "Business Relations Officer",
  "Business Support Officer",
  "Case Manager",
  "Clerk R12",
  "Client Account Administrator",
  "Client Services Advisor",
  "Contract Administrator",
  "Contract/Fin Administrator",
  "Corp Financial Administrator",
  "Correspondence Coordinator",
  "Cust Serv Rep-Aux. As & When",
  "Cust Serv Rep-Auxiliary",
  "Customer Serv Rep",
  "Customer Serv Representative",
  "Customer Serv. Representative",
  "Customer Service Assistant",
  "Customer Service Clerk",
  "Customer Service Rep",
  "Customer Service Rep - Ops",
  "Customer Service Rep 1/2 time",
  "Customer Service Rep-1/2 Time",
  "Customer Service Rep-3/4 time",
  "Customer Service Rep-part time",
  "Customer Service Rep.",
  "Customer Service Representativ",
  "Customer Services Assistant",
  "Customer Services Rep",
  "Disposal Clerk",
  "Finance and Admin Assistant",
  "Finance Clerk",
  "Finance Clerk R12",
  "Finance&Contract Administrator",
  "Financial Services Advisor",
  "Financial Services Clerk",
  "Gazette Coordinator",
  "Gazette Lead",
  "HR Coordinator",
  "HR Service Representative",
  "Intake Administrator",
  "Intake Reception",
  "Intake Receptionist",
  "Intake Support Clerk",
  "Internal Communications Coord",
  "Jr. Disposal Associate",
  "Junior Disposal Associate",
  "Material Master Cntrl Officer",
  "MPDP EFT Clerk",
  "Print Production Coordinator",
  "Procurement Administrator",
  "Program Asst/ Docs Coordinator",
  "Project Assistant",
  "Purchasing Buyer",
  "RAEG Project Assistant",
  "Records Technician",
  "Senior Admin Assistant",
  "Senior Customer Service Rep",
  "Senior Finance & Admin Clerk",
  "Sr. Administrative  Assistant",
  "Sr. Administrative Assistant",
  "Training Administrator",
  "AIR Warehouse Supervisor",
  "Bc Bid App Support Analyst",
  "BC Bid Support",
  "BC Bid Support Analyst",
  "Cash Management Officer",
  "Clerk R15",
  "Disposal Associate",
  "Forms Inventory Officer",
  "Information Control Officer",
  "Inventory Officer",
  "Investigation Officer",
  "Office Administrator",
  "Office Manager",
  "Office Manager, GRS",
  "Office Supervisor",
  "Parking Coordinator",
  "Program Administrator",
  "Program Analyst",
  "Project Manager",
  "Project Services Assistant",
  "Records Analyst",
  "Records Transfer Coordinator",
  "Refresh Coordinator",
  "Senior CSR",
  "Senior Customer Service Rep",
  "Senior Customer Service Rep.",
  "Senior Customer Services Rep",
  "Senior Disposal Associate",
  "Snr Customer Service Represent",
  "Sr Customer Service Rep",
  "Sr. Customer Service Rep",
  "Sr. Customer Service Rep.",
  "Supervisor",
  "Warehouse Supervisor",
  "Warehouse Supervisor/WAMS",
  "Mail/Data Entry Clerk",
  "As and When Postal Clerk",
  "Aux As/ When Postal Clerk",
  "Aux As/When Clerk R9",
  "Aux As/When Postal Clerk",
  "Clerk Postal R9",
  "Postal Clerk",
  "Postal Clerk Kamloops",
  "Postal Clerk Kelowna",
  "Postal Clerk Nanaimo",
  "Postal Clerk Nelson",
  "Postal Clerk Prince George",
  "Aux As/When Machine Operator",
  "Aux As/When Print Operator",
  "Card Production Operator",
  "Machine Operator",
  "Mail Preparation Clerk",
  "Postal Clerk",
  "Postal Clerk Lead Hand",
  "Postal Clerk, Lead Hand",
  "Variable Data Print Op Aux",
  "Variable Data Print Operator",
  "Clerk Postal R15",
  "Postal Clerk Lead Hand",
  "Printing Production Technician",
  "Team Lead",
  "Team Lead, Card Prod. and Scan",
  "Administrative Assistant",
  "Assistant to the Director",
  "Branch Coordinator",
  "Clerk Stenographer R9",
  "Finance & Admin Assistnt",
  "Finance & Admin Clerk",
  "Finance & Administration Clerk",
  "Finance and Admin clerk",
  "Financial Serv. Representative",
  "Program Assistant",
  "Project Assistant",
  "Senior Admin Assistant",
  "Branch Coordinator",
  "Branch Coordinator",
  "Executive Assistant",
  "Financial Services Advisor",
  "HR & Branch Coordinator",
  "Legal Assistant",
  "Office Coordinator Supervisory",
  "Office Manager",
  "Program Assistant",
  "Senior Admin. Assistant",
  "Senior Administrative Assistan",
  "Branch Operations Coordinator",
  "Office Manager",
  "Senior Writer",
  "Communications & Engage Coord",
  "Communications Officer",
  "Communications Officer R18",
  "Internal Comms Coordinator",
  "Internal Communication Coord.",
  "Internal Communications Coord",
  "Stkhldr Engagement & Evnt Lead",
  "Stkhldr, Engage & Event Lead",
  "Writer",
  "Change Management Strategist",
  "Client & Engagement Specialist",
  "Client and Business Coordinato",
  "Client Comms. Coordinator",
  "Client Communications Coord",
  "Client Engagement Specialist",
  "Client Rel. & Services Coord.",
  "Client Relations Coordinator",
  "Comm & Engagement Spec",
  "Comms & Client Relations Coord",
  "Communications Manager",
  "API Developer (Coop)",
  "Application Developer",
  "Bus Process & Procedure Writer",
  "Co-op Student",
  "Co-op student - Marketing",
  "Co-op Student 1",
  "Co-op Supply Chain Analyst",
  "Comms Designer, Coop Lvl 1",
  "Communications & Engagement",
  "Coop Education Train Progm Lv1",
  "Coop Lv1 - Software Developer",
  "COOP LVL 1 ORCS Inventory",
  "Coop Student",
  "Coop Student Financial Analyst",
  "Finance and Admin Clerk",
  "Investigative Analyst",
  "Network Analyst Co-op Level 1",
  "Policy Analyst Co-op",
  "Policy Analyst, Co-op Lvl 1",
  "Records Analyst",
  "Security Co-Op Business Analys",
  "Security Co-Op Technical Analy",
  "Strategic Design & Transform",
  "Sustainability Analyst (Co-op)",
  "Application Developer",
  "Archivist",
  "Business Analyst",
  "Co-op Student",
  "Co-op Student Level 2",
  "Coop Economic Analyst",
  "Coop Education Train Prgm Lv2",
  "Coop Education Train Progm Lv2",
  "Coop Student",
  "Coop Training Level 2",
  "Coop User Exp Specialist",
  "Economics Co Op",
  "Emerg Plan & Resp Coordinator",
  "Investigative Analyst",
  "Privacy Analyst",
  "Strat & Dig Program Mgmt Coop",
  "Deputy Minister",
  "Manager, Electronic Publishing",
  "Economist",
  "Economist, Satellite Accounts",
  "Population Analyst",
  "Analyst, Immigration",
  "Ec27_Sr. Telecom Fin. Analyst",
  "Economist",
  "Lead, Data & Wharehs Develop.",
  "Sr Portfolio Investment Anlyst",
  "Workforce Planning Advisor",
  "Economist  R30",
  "Senior Economist",
  "Mgr, Business and Econ Stats",
  "Editor",
  "Assessment Marking Coordinator",
  "Executive Administrative Asst",
  "Financial Analyst",
  "Financial/Research Analyst",
  "Project Accountant",
  "Capital Financial Analyst",
  "Client Services Supervisor",
  "Fin Analyst (Developmental)",
  "Financial Analyst",
  "Financial Analyst IM/IT Capita",
  "Financial Analyst, Accounting",
  "Financial Business Analyst",
  "Financial Officer",
  "Financial Services Supervisor",
  "Revenue Analyst",
  "Accounts& Bus. Systems Manager",
  "Fin Analyst, Delivery Manage",
  "Financial Analyst",
  "Financial Analyst - Accounting",
  "Financial Analyst, Budgets",
  "Financial Analyst, CMU",
  "Financial Business Analyst",
  "Financial Officer",
  "Financial Officer, Budgets",
  "Revenue Analyst",
  "Senior Budget Analyst",
  "Senior Financial Analyst",
  "Sr Policy & Controls Advisor",
  "Sr. Fin Policy Analyst - PA",
  "Sr. Policy & Controls Advisor",
  "Capital Financial Analyst",
  "Financial Analyst",
  "Financial Compliance Analyst",
  "Manager, Finance and Admin",
  "Mgr, Business Integration",
  "Senior Financial Analyst",
  "Senior Financial Officer",
  "Sr Fin Analyst, Bud & Corp Rep",
  "Sr Fin. Anl. Budg. & Corp. Rep",
  "Team Lead, Budgets & Acct.",
  "Team Lead, Budgets & Acct'g",
  "Team Lead, Budgets&Accounting",
  "Sr, Financial Analyst",
  "Team Lead, Fin & Econ Models",
  "Senior Accounting Advisor",
  "Senior Financial Analyst",
  "Senior Financial Officer",
  "Sr Financial Analyst",
  "Sr. Financial Analyst",
  "Team Lead, Budgets Accounting",
  "Foreman R15",
  "Programmer",
  "Systems Support Analyst",
  "Asset Management Technician",
  "Stockroom Clerk",
  "Asset Mgmt TechnicianTeam Lead",
  "Order Integrity",
  "Full Stack Developer Lvl 1",
  "GIS Programmer Analyst",
  "Graphic Designer",
  "Identity Services Analyst",
  "Jr Service Analyst",
  "Jr. Security Privacy Analyst",
  "Jr.Tech & Ops Support Analyst",
  "Junior Business Analyst",
  "Junior Service Analyst",
  "Junior Technical Consultant",
  "MPDP Applications Oper. Analys",
  "Network Support Analyst",
  "Operations Support Analyst",
  "Security Analyst",
  "Service Coordinator",
  "Service Desk Analyst",
  "Service Desk Technical Analyst",
  "Software Licensing Analyst",
  "Technical Support Analyst",
  "Web Analyst",
  "Web LAN & SharePoint Tech Anal",
  "Web Technical Analyst",
  "Application Management Analyst",
  "Asset Management Analyst",
  "Business Analyst",
  "Client Support Analyst",
  "Content Designer",
  "Content Strategist",
  "Customer Support Analyst",
  "Data Analyst",
  "DevOps Specialist",
  "Document Systems Analyst",
  "Documents & Print System Ana.",
  "Full Stack Developer (Level 2)",
  "Infrastructure Analyst",
  "ISL21 Technical Analyst",
  "Junior Business Analyst",
  "Network Problem Analyst",
  "Network Security Analyst",
  "Programmer Analyst",
  "Programming Analyst",
  "Project Analyst",
  "Qual Assur Tester/Busin Analys",
  "Security Analyst",
  "Senior VPN Support Analyst",
  "Service Analyst",
  "Service Analyst & Procurement",
  "Service Operations Analyst",
  "System Analyst",
  "Systems Analyst",
  "Systems Support Analyst",
  "Systems/SaaS Analyst",
  "Technical  Analyst",
  "Technical Analyst",
  "Technical Change Coordinator",
  "Technical Support Analyst",
  "Test Analyst",
  "Web Programmer Analyst",
  "Application Analyst",
  "Bus Analyst, Order Data Mngmnt",
  "Business Analyst",
  "Business Analyst, Hosting Serv",
  "Business Operations Analyst",
  "Change Management Lead",
  "Client Relations Manager",
  "Client Support Coordinator",
  "Content Design Lead",
  "Customer Support Coord",
  "Data Administrator",
  "Data Analyst",
  "Data Implementer",
  "Data Netwoork Coordinator",
  "Data Network Analyst",
  "Data Network Coordinator",
  "Database Analyst",
  "Digital Content Lead",
  "Drawings Database Analyst",
  "Ent Software Lic & Comp Spec",
  "Full Stack Developer",
  "Full Stack Developer - Level 3",
  "Full Stack Developer Level 3",
  "Full Stack Developer Lvl 3",
  "Governance & Strategy Analyst",
  "Information Systems R24",
  "Int Programmer Analyst",
  "Inter Full Stack Developer",
  "Interm Full Stack Developer",
  "Interme Infrastructure Analyst",
  "Intermed  Programmer Analyst",
  "Intermed Programmer Analyst",
  "Intermed Systems/SaaS Analyst",
  "Intermed. Programmer Analyst",
  "Intermedi Full Stack Developer",
  "Intermediate Business Analyst",
  "Intermediate Developer, Java",
  "Intermediate Full Stack Dev",
  "Intermediate Full Stack Dev.",
  "Intermediate Prog Analyst",
  "Intermediate Programmer Analys",
  "Intermediate Programmer Anlst.",
  "Intermediate Programmer Anlyst",
  "Intermediate ProgrammerAnalyst",
  "Intermediate Stack Dev - Lv3",
  "Intermediate Stack Developer",
  "Intermediate Tech Analyst",
  "Intermediate Technical Analyst",
  "IT Project Lead",
  "Manager, IT Disposal",
  "MPDP Business Analyst",
  "MPDP Systems Developer",
  "Network Analyst",
  "Network Systems Analyst",
  "Operations Service Lead",
  "Procurement Project Coord",
  "Product Business Analyst",
  "Product Portfolio Analyst",
  "Program Management Analyst",
  "Programmer Analyst",
  "Project Service Assistant",
  "Quality Assurance Analyst",
  "Quality Assurance Lead",
  "Scrum Master",
  "Scrum Master - Technical",
  "Scrum Master (technical)",
  "Scrum Master Technical",
  "Scrum Master, Strat Priorities",
  "Security Analyst",
  "Security Analyst",
  "Security and Privacy Analyst",
  "Security/Privacy Analyst",
  "Senior Business Analyst",
  "Senior Content Designer",
  "Senior IT Project Mgmt Analyst",
  "Senior Systems Analyst",
  "Senior Systems SaaS Analyst",
  "Senior Systems Support Analyst",
  "Service Analyst",
  "Service Design Specialist",
  "Service Designer",
  "Software As A Service Mngr.",
  "Software Licensing Specialist",
  "Software Service Products Mgr",
  "Sr Project Management Analyst",
  "Sr Tech Anylst ALM Tools Splst",
  "Sr, IT Procurement Specialist",
  "Sr. Network Tech Consultant",
  "Supervisor Service Desk",
  "Supervisor, IT Ops Support",
  "Supervisor, Service Operations",
  "Systems Analyst",
  "Tech Analyst, Config. Mgt",
  "Technical Analyst",
  "Technical Business Analyst",
  "Technical Lead",
  "Technology Bus Analyst",
  "Technology Business Analyst",
  "Training Specialist",
  "UC Consultant",
  "User Exp Design, Info Arc Lead",
  "User Exper Design - UX Lead",
  "USER EXPERIENCE DESIGN:UX LEAD",
  "User Experience Designer",
  "UX Designer",
  "UX Digital Content Lead",
  "Voice Applications Consultant",
  "Voice Technical Analyst",
  "'Senior Business Analyst",
  "Application Developer",
  "Bus. Analysis / Proj. Manager",
  "Business Analyst",
  "Business Intelligence Architec",
  "Business Services Analyst",
  "Business Solutions Architect",
  "Client Integration Specialist",
  "Client Services Manager",
  "Corporate Applications Analyst",
  "Data Admin & Model Repos Mgr",
  "Data Analyst",
  "Data Architect",
  "Data Warehouse Architect",
  "Database Administrator",
  "Database Analyst",
  "Design Lead",
  "Dev Operations Specialist",
  "Dev Ops Specialist",
  "Develop Ops Specialist",
  "DevOps Plaftform Specialist",
  "DevOps Specialist",
  "DevOpsSpec Online Serv Solutns",
  "Digital Analyst",
  "Engage&Change Initiatives Lead",
  "Ent Software Lic & Comp Spec",
  "Enterprise Architect",
  "Full Stack Developer",
  "Full Stack Developer - Level 4",
  "Full Stack Developer Level 4",
  "Full Stack Developer Lvl 4",
  "Full Stack Developer-Level 4",
  "GeoWeb Architect",
  "IM/IT Procurement Architect",
  "IMIT Procurement Architect",
  "IMIT Procurement Lead",
  "Incident Management Supervisor",
  "Information Systems R27",
  "IS27 Full Stack Developer",
  "IT Contract Specialist",
  "Lead Application Support",
  "Lead Business Analyst",
  "Lead Remot Access Support",
  "Manager, Virtual Asst Tech",
  "Mob App Dev Ops Specialist",
  "MPDP Architect",
  "MPDP Server Administrator",
  "Network Data Steward",
  "Network Request Consultant",
  "Platform Administrator",
  "Portfolio Project Manager",
  "Prod Mgr, Engagement Platforms",
  "Product Owner",
  "Project Lead",
  "Quality Assurance Lead",
  "Scrum Master - Technical",
  "Scrum Master, Technical",
  "Search & Applications Manager",
  "Senior Application Analyst",
  "Senior Application Architect",
  "Senior Application Developer",
  "Senior Application Lead",
  "Senior Business Analyst",
  "Senior Data Architect",
  "Senior Data Mgmt Analyst",
  "Senior Database Administrator",
  "Senior Full Stack Developer",
  "Senior Info Privacy Analyst",
  "Senior IT Business Analyst",
  "Senior IT Project Lead",
  "Senior Network Analyst",
  "Senior Privacy Analyst",
  "Senior Product Analyst",
  "Senior Programmer Analyst",
  "Senior Project Analyst",
  "Senior Project Manager",
  "Senior Scrum Master",
  "Senior Scrum Master -Technical",
  "Senior Scrum Master Technical",
  "Senior Security Analyst",
  "Senior Security Analyst",
  "Senior Service  Analyst",
  "Senior Service Analyst",
  "Senior Solutions Developer",
  "Senior Systems Analyst",
  "Senior Systems Architect",
  "Senior Technical Analyst",
  "Senior Technical Service Lead",
  "Senior Technology Analyst",
  "Senior Test Analyst",
  "Senior User Experience Designe",
  "Senior UX Designer",
  "Senior UX Practitioner",
  "Service Design Lead",
  "Service Designer",
  "Service Designer Lead",
  "Service Integrator",
  "Service Lead",
  "Service Management Analyst",
  "Service Manager",
  "Site Reliability Specialist",
  "Site Reliability SpecialistDES",
  "Snr Business Analyst",
  "Sr BC Services Card BA",
  "Sr Business Analyst",
  "Sr Data Architect, DSS",
  "Sr Governance & Strat Analyst",
  "Sr Ministry Info Priv Analyst",
  "Sr Network Security Analyst",
  "Sr Programmer Analyst",
  "Sr Programming Analyst",
  "Sr Project Manager",
  "Sr Scrum Master - Technical",
  "Sr Scrum Master (Technical)",
  "Sr Service Support Analyst",
  "Sr Tech Analyst, Config Mgmt",
  "Sr Technical Analyst",
  "Sr Technical Analyst Dynamics",
  "Sr Technical Analyst JIRA",
  "Sr Telecommunications Analyst",
  "Sr. Advisor Service Experience",
  "Sr. Full Stack Developer",
  "Sr. Full Stack Developer Lvl 4",
  "Sr. Infrastructure Analyst",
  "Sr. Ministry Info Priv Analyst",
  "Sr. Product Business Analyst",
  "Sr. Scrum Master",
  "Sr. Scrum Master (Technical)",
  "Sr. Security Analyst",
  "Sr. Service Analyst",
  "Sr. Spatial Data Administrator",
  "Sr. Systems/SaaS Analyst",
  "Sr. Tech Analyst Sharepoint",
  "Sr. Tech. Analyst Sharepoint",
  "Sr. Technical Business Analyst",
  "Sr. User Experience Designer",
  "Team Lead - Data Network Coord",
  "Team Lead Bus Analyst",
  "Team Lead Network Implementati",
  "Team Lead Network Operations",
  "Team Lead Serv Design Spec",
  "Team Lead, Business Analysis",
  "Team Lead, Business Analyst",
  "Technical Architect",
  "Technical Integration Speclst.",
  "Technical Operations Lead",
  "TL Web Gov & Content Strategy",
  "TL Web Gov & Digital Access",
  "UX and Service Design",
  "UX and Service Design Lead",
  "UX Experience and Service Desi",
  "Warehouse Content Mgmt",
  "Web Mapping Infra Services",
  "App Architect & Tech Team Lead",
  "Application Developer (Regist)",
  "Application Manager",
  "Architect",
  "Chapter Lead DevOps",
  "Client Advisor/Project Manager",
  "Client Integration Manager",
  "Client Onboarding Manager",
  "Client Onboarding Mgr, BCeID",
  "Cloud Identity & Acc Mgmt Arch",
  "Cloud Security Architect",
  "Cloud Security Operations Arch",
  "Database Administrator",
  "Development Mgr&Solution Arch",
  "Enterprise Architect",
  "Enterprise Architect,Info Mgmt",
  "Full Stack Developer",
  "IM/IT Gov & Strat Team Lead",
  "Infrastructure Team Lead",
  "Lead Bus Analysis & Proj Mgmt",
  "Lead Srvce & Transit. Planning",
  "Lead Technical Architect",
  "Lead, Sr. IM/IT Project Mgr",
  "Manager, Business Continuity",
  "Manager, Business Operations",
  "Manager, Business Services",
  "Manager, Change Management",
  "Manager, ICT Facilities",
  "Manager, Problem Management",
  "Manager, Solution Design",
  "Mgr, CSC & Incident Management",
  "Mgr, Ntwk Ops & Implementation",
  "Min. Info Security Officer",
  "MISO, Architect",
  "MPDP Sr App Tech Specialist",
  "Network Comm Architect",
  "Network Comms Architect",
  "Network Security Architect",
  "Netwrk Communication Architect",
  "Order Service Manager",
  "Portfolio Lead",
  "Portfolio Manager",
  "Privacy Officer MPO",
  "Product Manager",
  "Product Owner",
  "Product Portfolio Manager",
  "Project Portfolio Manager",
  "Security Architect",
  "Senior App Developer-Team Lead",
  "Senior Application Architect",
  "Senior Application Specialist",
  "Senior Architect",
  "Senior Business Analyst",
  "Senior Business Consultant",
  "Senior Cloud Architect",
  "Senior Database Administrator",
  "Senior Database Analyst",
  "Senior Digital Analyst",
  "Senior Enterprise Architect",
  "Senior Identity Architect",
  "Senior Integration Architect",
  "Senior Lead, Change Management",
  "Senior Mobile Messaging Archit",
  "Senior Platform Administrator",
  "Senior Portfolio Manager",
  "Senior Project Manager",
  "Senior Security Architect",
  "Senior Security Specialist",
  "Senior Services Manager",
  "Senior Team Lead",
  "Senior Team Leader",
  "Senior Technical Analyst",
  "Senior Technical Architect",
  "Senior Technical Specialist",
  "Senior Telecom Specialist",
  "Senior TL, Business Analysis",
  "Service Manager",
  "Service Manager-Device Serv.",
  "Service Manager-Device Service",
  "Service Manager-Workstations",
  "Service Manager, Messaging",
  "Service Mgr, Confr. Services",
  "Site Reliability Spec Lead",
  "SiteMinder Ops Team Leader",
  "Solution Architect",
  "Solutions Architect",
  "Solutions Architect, Messaging",
  "Solutions Architect, SharePt.",
  "Sr Advisor, Business Agility",
  "Sr Enterprise Cloud Architect",
  "Sr Lead, CSC & Incident Mgmt",
  "Sr Mainframe Program Analyst",
  "Sr Proj Manager/ Bus Analyst",
  "Sr Team Lead Business Analysis",
  "Sr Team Lead-Business Analysis",
  "Sr Team Lead, Business Analyst",
  "Sr Technical Architect",
  "Sr Telecommunications Analyst",
  "Sr TL, Research & Bus Analysis",
  "Sr. Application Database Admin",
  "Sr. Bus. Intelligence Analyst",
  "Sr. Business Consultant",
  "Sr. Cloud Solution Architect",
  "Sr. Database Administrator",
  "Sr. Digital Architect",
  "Sr. Product Manager",
  "Sr. Product Portfolio Manager",
  "Sr. Project & Business Analyst",
  "Sr. Security Specialist",
  "Sr. Team Lead, Bus Analysis",
  "Sr. Technical Architect",
  "Sr. Telecommunications Spec",
  "Team Lead",
  "Team Lead CSAM",
  "Team Lead IM-IT Gov & Strategy",
  "Team Lead, Architect",
  "Team Lead, Client Engagement",
  "Team Lead, IM/IT Service Ops",
  "Team Lead, Service Delivery",
  "Team Lead/Architect",
  "TeamLeadNtwkSecurityArchitect",
  "TL  IM-IT Governance & Strateg",
  "TL IMIT Governance & Strategy",
  "TL, Data Architecture Servs",
  "TL, IMIT Governance & Strategy",
  "TL, Sr Solutions Architect",
  "Data Management Associate",
  "Indigenous Youth Intern",
  "Indigenous Youth Intern Prog",
  "IT Coordinator",
  "Compositor",
  "Lab Assistant",
  "Pharmacy Assistant",
  "Pharmacy Technician",
  "Senior Developer",
  "Lead Systems Analyst",
  "Senior Systems Analyst",
  "Team Lead",
  "Chief Contract Executive",
  "Sr Advisor, ASD Proj Sec",
  "Exec Dir, Corp Plan & Perf",
  "Office Assistant 2",
  "Receptionist",
  "Registries Support Clerk",
  "Stock Worker",
  "Supply Chain Analyst",
  "Pharmacist",
  "Pharmacist 2",
  "Assistant Manager, Pharm Ops",
  "Manager, Pharmacy",
  "Senior Policy Analyst",
  "Policy Analyst",
  "Senior Policy Analyst",
  "Senior Policy Analyst, Digital",
  "Sr Leg and Policy Analyst",
  "Sr Pol & Stakeholder Rel Adv",
  "Sr Policy Analyst",
  "Sr Policy Analyst, Insights",
  "Sr Privacy and Policy Analyst",
  "Sr. Leg & Policy Analyst",
  "Sr. Leg. & Policy Analyst",
  "Sr. Leg. And Policy Analyst",
  "Sr. Privacy and Policy Analyst",
  "Pre-Press Technician",
  "Developer",
  "Programmer Analyst",
  "Systems Analyst",
  "Privacy Analyst",
  "Research Officer R15",
  "Project Administrator",
  "Data Analyst",
  "Demographic Analyst RO N21",
  "Junior Researcher Analysis",
  "Data Analyst",
  "Project Analyst",
  "Research Analyst",
  "Research Officer",
  "Research Officer R24",
  "Senior Data Analyst",
  "Senior Research Analyst",
  "Senior Research Officer",
  "Sr Research Analyst",
  "Web Data Analyst Webmaster",
  "Data Science Fellow",
  "Data Scientist",
  "Research Manager",
  "Research Project Lead",
  "Senior Data Scientist",
  "Senior Researcher",
  "Senior Data Scientist",
  "RPO3 Real Estate Advisor",
  "Senior Manager, Sustainability",
  "Manager, Properties",
  "Real Estate Advisor",
  "RPO2 Real Estate Advisor",
  "Oversight Project Officer",
  "Real Property Officer 3",
  "Snr Mgr, Environmental Mgnt Sy",
  "Sr. Mgr.,Sustainability Init.",
  "SrMgr Health & Safety Mgmt Sys",
  "BTA Security",
  "Build.Tech.Advisor-Mechanical",
  "Building Tech Adv (Electrical)",
  "Building Tech Adv (Mechanical)",
  "Building Tech Adv (Security)",
  "Building Tech Advisor, Energy",
  "Senior Executive Assistant",
  "Secondment In",
  "Science Fellow Prog (MITACS)",
  "Sr App Dev/ Supervisor",
  "AIR Stock Worker",
  "AIR Stockworker",
  "Asset Inv.Recovery Stockworker",
  "Asset Invest Rec Stock Worker",
  "AsstInvstmtRecvry/DC Stk Wrkr",
  "Inventory Technician",
  "Stock Worker",
  "Stockworker",
  "Stockworker R9",
  "Stores Worker",
  "Stores Worker, Recycling",
  "BC Auction Rep",
  "Lead Hand",
  "Line Supervisor",
  "Listing Agent",
  "Warehouse, Lead Hand",
  "Assistant Manager, Warehouse",
  "Supervisor,Logis. & Warehouse",
  "Vehicle Supervisor",
  "Warehouse Sup, Logistics",
  "Warehouse & Logistics Supervr",
  "Drawings Technician",
  "Environmental Coordinator",
  "Spatial Data Analyst",
  "Geomatics Specialist",
  "GIS Specialist",
  "Permitting Specialist",
  "Sr. Advisor, Indigen. Relation",
  "Ex.Dir.,Service Transformation",
  "Exec. Dir., Relationship Mgmt",
  "Exec.Dir., Serv Integr &Oper",
  "ExecDir,Transform&Technology",
  "Executive Director",
  "Executive Director - Finance",
  "Executive Director, Open Gover",
  "Executive Project Director",
  "Negotiation Lead",
  "Strategic Leadership",
  "Supervisor, Content Editing",
  "XML Editor",
  "Data Management Project Assist",
  "Operations Analyst",
  "Program Assistant",
  "Project Assistant",
  "Research Assistant",
  "Social Sustain Project Asst",
  "XML Editor",
  "Summer Intern",
];

const getRandomInt = (min: number, max: number) => {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

export const getBands = async (req: Request, res: Response) => {
  return res.status(200).json(bands);
};

export const getTitles = async (req: Request, res: Response) => {
  return res.status(200).json(titles);
};

export const getMinistries = async (req: Request, res: Response) => {
  return res.status(200).json(ministries);
};

const createFakeHistory = () => ({
  positionNumber: `${getRandomInt(0, 9)}${getRandomInt(0, 9)}${getRandomInt(
    0,
    9
  )}${getRandomInt(0, 9)}${getRandomInt(0, 9)}${getRandomInt(
    0,
    9
  )}${getRandomInt(0, 9)}${getRandomInt(0, 9)}`,
  title: titles[getRandomInt(0, titles.length - 1)],
  ministry: ministries[getRandomInt(0, ministries.length - 1)],
  band: bands[getRandomInt(0, bands.length - 1)],
});

export const getHistory = async (req: Request, res: Response) => {
  const fakeData = [
    createFakeHistory(),
    createFakeHistory(),
    createFakeHistory(),
    createFakeHistory(),
    createFakeHistory(),
    createFakeHistory(),
    createFakeHistory(),
    createFakeHistory(),
    createFakeHistory(),
  ];
  return res.status(200).json(fakeData);
};

const flip = () => {
  return getRandomInt(0, 1) % 2 == 0;
};

export const searchPositionNumber = async (req: Request, res: Response) => {
    const history = createFakeHistory();
    const fakeData = {
      title: history.title,
      ministry: history.ministry,
      band: history.band,
    };
    return res.status(200).json(fakeData);
};

export const postSubmission = async (req: Request, res: Response) => {
  res.status(201).send();
};

const createFakeRole = (salary: number) => ({
  title: titles[getRandomInt(0, titles.length - 1)],
  ministry: ministries[getRandomInt(0, ministries.length - 1)],
  band: bands[getRandomInt(0, bands.length - 1)],
  salary: flip()
    ? salary + getRandomInt(1000, 30000)
    : salary - getRandomInt(1000, 30000),
});

export const getSubmission = async (req: Request, res: Response) => {
  const salary = getRandomInt(60000, 110000);

  const fakeData = {
    ...createFakeHistory(),
    experience: getRandomInt(1, 4),
    comments: "Wow, look at these comments!",
    similarRoles: [
      createFakeRole(salary),
      createFakeRole(salary),
      createFakeRole(salary),
      createFakeRole(salary),
      createFakeRole(salary),
    ],
    supervisorSalary: salary + getRandomInt(1000, 30000),
    bcPubAvg: salary + getRandomInt(1000, 10000),
    ministryAvg: salary + getRandomInt(1000, 10000),
    divisionAvg: salary + getRandomInt(1000, 10000),
    suggestion: salary,
  };
  return res.status(200).json(fakeData);
};
